defmodule Shop2.Repo.Migrations.AddProductsAndCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text, null: false
      add :image, :text
      add :price, :money_with_currency, null: false
      add :quantity_stored, :bigint, null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "products_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:products, "products_category_id_fkey")

    drop table(:products)
  end
end
